Bottle v0.12.13 server starting up (using AutoServer())...
Listening on http://0.0.0.0:80/
Hit Ctrl-C to quit.

182.254.86.149 - - [15/Apr/2018 17:49:39] "POST /?signature=0b3d94e0a2716adb6dc8819e2edb9a54bb53716d&timestamp=1523785779&nonce=1230261702&openid=o2NddxCv3BSIW_nS5-7JhYgO6I5c HTTP/1.1" 200 467
182.254.86.154 - - [15/Apr/2018 17:49:47] "POST /?signature=aedd079eed5a3203c5e77685ae62158c9e51ee66&timestamp=1523785787&nonce=438322169&openid=o2NddxHhZloQV55azmx8zVXv9mAQ HTTP/1.1" 200 467
182.254.86.149 - - [15/Apr/2018 17:49:48] "POST /?signature=2157457bbdade8a47c538e4a0eda725024c9b75c&timestamp=1523785788&nonce=1196454146&openid=o2NddxHhZloQV55azmx8zVXv9mAQ HTTP/1.1" 200 326
[E 180415 17:49:49 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
[W 180415 17:49:49 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a2d52c>
182.254.86.154 - - [15/Apr/2018 17:49:49] "POST /?signature=8aade39b2c15eace7efddfdc3926da0b65768882&timestamp=1523785789&nonce=599463756&openid=o2NddxHhZloQV55azmx8zVXv9mAQ HTTP/1.1" 200 0
[E 180415 17:49:51 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
[W 180415 17:49:51 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a2db8c>
182.254.86.149 - - [15/Apr/2018 17:49:51] "POST /?signature=08520f2a61c72aa2202d5049df98dc89cdbfb6ed&timestamp=1523785791&nonce=547265518&openid=o2NddxHhZloQV55azmx8zVXv9mAQ HTTP/1.1" 200 0
[E 180415 17:49:53 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
[W 180415 17:49:53 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a2de8c>
182.254.86.144 - - [15/Apr/2018 17:49:53] "POST /?signature=3291068a7fad98000afc0c25d333a10309c69f6c&timestamp=1523785793&nonce=1930697099&openid=o2NddxHhZloQV55azmx8zVXv9mAQ HTTP/1.1" 200 0
[E 180415 17:49:54 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
[W 180415 17:49:54 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a2dfec>
182.254.86.139 - - [15/Apr/2018 17:49:54] "POST /?signature=1f084b2523afebaa26746c90024f139a18ff02a1&timestamp=1523785794&nonce=1773377657&openid=o2NddxPLY0J741NUPhriTE3rZ4J0 HTTP/1.1" 200 0
[W 180415 17:49:56 robot:419] No handler responded message <werobot.messages.events.UnSubscribeEvent object at 0xb6a4f44c>
182.254.86.144 - - [15/Apr/2018 17:49:56] "POST /?signature=972e72e486bfcda5c12f8abe63667ce67982a9c2&timestamp=1523785796&nonce=1253839716&openid=o2NddxC-4pJ5NQmNHOuS2B40W1j8 HTTP/1.1" 200 0
[E 180415 17:50:11 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
[W 180415 17:50:11 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a4f80c>
182.254.86.154 - - [15/Apr/2018 17:50:11] "POST /?signature=4696e03c8e72ff9e40773d0132cfebb273030cb8&timestamp=1523785811&nonce=354457063&openid=o2NddxPLY0J741NUPhriTE3rZ4J0 HTTP/1.1" 200 0
[W 180415 17:50:14 robot:419] No handler responded message <werobot.messages.events.ViewEvent object at 0xb6a4fa8c>
182.254.86.150 - - [15/Apr/2018 17:50:14] "POST /?signature=268ce70485805e2001d61cb4fb6aed3c5c0aa91d&timestamp=1523785814&nonce=693468733&openid=o2NddxDfL_lm1EFqKvXYU0iYSw3c HTTP/1.1" 200 0
[E 180415 17:50:16 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
[W 180415 17:50:16 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a4fe4c>
182.254.86.139 - - [15/Apr/2018 17:50:16] "POST /?signature=ec45dc1fe8c38855a75149f0513ed13f6318e27b&timestamp=1523785816&nonce=1710997376&openid=o2NddxCv3BSIW_nS5-7JhYgO6I5c HTTP/1.1" 200 0
[W 180415 17:50:28 robot:419] No handler responded message <werobot.messages.events.ViewEvent object at 0xb6a4fecc>
182.254.86.154 - - [15/Apr/2018 17:50:28] "POST /?signature=50413658665f37377eee45024c51aca861e0bbb5&timestamp=1523785828&nonce=1770307732&openid=o2NddxPLY0J741NUPhriTE3rZ4J0 HTTP/1.1" 200 0
[E 180415 17:50:29 robot:405] Catch an exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/werobot/robot.py", line 399, in get_reply
        reply = handler(*args)
      File "reply_from_pymysql.py", line 101, in hello
        print('\u300a%s\u300b'%message.content)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
[W 180415 17:50:29 robot:419] No handler responded message <werobot.messages.messages.TextMessage object at 0xb6a514ac>
182.254.86.149 - - [15/Apr/2018 17:50:29] "POST /?signature=875f8bf09f36746a3b43b7239b7e3d438141f675&timestamp=1523785829&nonce=1339780745&openid=o2NddxCv3BSIW_nS5-7JhYgO6I5c HTTP/1.1" 200 0
[W 180415 17:50:38 robot:419] No handler responded message <werobot.messages.events.ViewEvent object at 0xb6a5172c>
